### ISSUE TITLE
安装后luci界面显示PermissionError 没有权限

### ISSUE THREAD

**Issue by madokaisbest** [tty228/luci-app-navidrome#1]
chmod -R 755 /etc/init.d/navidrome之后提示依旧，重启也不能解决。
日志界面提示Fri Dec 15 23:50:28 2023 daemon.info procd: Not starting instance navidrome::instance1, command not set
执行/etc/init.d/navidrome reload 提示
Command failed: Not found
Navidrome is not enabled. Exiting...

**Comment by tty228** [comment]
OpenWrt 的版本是？

**Comment by madokaisbest** [comment]
> OpenWrt 的版本是？

忘记提前说明了，抱歉。固件是自己编译的。
目标平台 | x86/64
固件版本 | OpenWrt SNAPSHOT r24164-67ce60c5f9 / LuCI Master git-23.341.48808-aa06da6
内核版本 | 6.1.67

**Comment by tty228** [comment]
你在系统日志里面看一下有什么错误提示
你那边是日志框不能显示，还是设置页面也不能显示？

日志框的权限需要修改一下这里，然后重启
/usr/share/rpcd/acl.d/luci-app-navidrome.json

https://github.com/tty228/luci-app-navidrome/blob/main/root/usr/share/rpcd/acl.d/luci-app-navidrome.json
（不知道为什么我这边不需要添加这个权限就可以运行）

**Comment by madokaisbest** [comment]
luci界面显示如下
![image](https://github.com/tty228/luci-app-navidrome/assets/73716241/31c98852-a1f6-4071-9181-64f44d312bba)
![image](https://github.com/tty228/luci-app-navidrome/assets/73716241/f92df844-2a4d-42db-be8d-a57d1a4ba88a)
重新安装会提示
![image](https://github.com/tty228/luci-app-navidrome/assets/73716241/faa7f146-1cbc-4e9b-bac9-d29549ab238e)
系统日志我看了一下，没有任何相关的信息。

**Comment by tty228** [comment]
SNAPSHOT 又改了什么权限方面的东西吗，我刚刚拿来测试的固件是 这个版本
OpenWrt SNAPSHOT r24660-c22aa0be3e / LuCI Master git-23.343.78641-c5b5640

那个版本的话，一开始日志框没有权限读取，别的倒是正常

![Screenshot_2023-12-16-23-22-39-56_a87fd7db6caa850b517aa6fa9d2fcd0e](https://github.com/tty228/luci-app-navidrome/assets/33397881/cdd29c38-10e4-4e3d-929f-7fe11a591763)

**Comment by tty228** [comment]
你试试 https://github.com/tty228/luci-app-navidrome/releases/tag/v1.3 这个能不能运行

**Comment by madokaisbest** [comment]
> 你试试 https://github.com/tty228/luci-app-navidrome/releases/tag/v1.3 这个能不能运行

![image](https://github.com/tty228/luci-app-navidrome/assets/73716241/e3a8ab81-8374-4289-a5f7-6524c4db6376)
![image](https://github.com/tty228/luci-app-navidrome/assets/73716241/da068b59-fb79-4333-ac48-a16e03245621)
还是不行。

**Comment by tty228** [comment]
你的固件邮箱发我一份看看，我试了几个固件都没这个问题
tty228@yeah.net

建议更换默认主题+浏览器隐私模式看看

**Comment by tty228** [comment]
或者不想纠结原因的话，修改配置文件
/etc/config/navidrome
MusicFolder 音乐文件目录
DataFolder 数据库目录
CacheFolder 缓存目录
然后执行 `/etc/init.d/navidrome start`
```
config navidrome 'config'
	option MusicFolder '/opt/music'
	option DataFolder '/opt/navidrome'
	option CacheFolder '/opt/navidrome/cache'
	option ScanSchedule '@every 24h'
	option TranscodingCacheSize '100MB'
	option ImageCacheSize '100MB'
	option Address '0.0.0.0'
	option Port '4533'
	option LogLevel 'warn'
	option Program_path '/usr/share/navidrome/navidrome'
	option Enable '1'
```

**Comment by madokaisbest** [comment]
> 你的固件邮箱发我一份看看，我试了几个固件都没这个问题 [tty228@yeah.net](mailto:tty228@yeah.net)
> 
> 建议更换默认主题+浏览器隐私模式看看

用网易邮箱发了一个固件给您。

**Comment by madokaisbest** [comment]
> 或者不想纠结原因的话，修改配置文件 /etc/config/navidrome MusicFolder 音乐文件目录 DataFolder 数据库目录 CacheFolder 缓存目录 然后执行 `/etc/init.d/navidrome start`
> 
> ```
> config navidrome 'config'
> 	option MusicFolder '/opt/music'
> 	option DataFolder '/opt/navidrome'
> 	option CacheFolder '/opt/navidrome/cache'
> 	option ScanSchedule '@every 24h'
> 	option TranscodingCacheSize '100MB'
> 	option ImageCacheSize '100MB'
> 	option Address '0.0.0.0'
> 	option Port '4533'
> 	option LogLevel 'warn'
> 	option Program_path '/usr/share/navidrome/navidrome'
> 	option Enable '1'
> ```

加了最后一行确实能用了，哈哈👏，就是luci界面还是报错。

**Comment by tty228** [comment]
/usr/libexec/navidrome-call 这个文件不知道为什么权限会出问题，你运行一下 `chmod +x /usr/libexec/navidrome-call` 就可以了

我这边的机子不会这样，看了一下，github 上的文件权限是正常的

$ git ls-files --stage
100755 1c26d8227295ab63c44204c016fa777888a8a740 0       navidrome-call

而且比较诡异的是，更改过权限之后，无论怎么卸载重装，权限都是正常的，不知道什么 bug

另外，我看你编译的固件已经包含了 docker，navidrome 是有 docker 版本的

**Comment by madokaisbest** [comment]
本来我也打算起docker的，偶然搜索到了您的项目想说这样部署起来也不错😄，给了权限之后现在完全正常了。
